### ISSUE TITLE
Please Release Version: 5.1.1

### ISSUE THREAD

**Issue by Vity01** [webjars/visjs#12]
Thank you.

**Comment by jamesward** [comment]
I'm not seeing that release at: https://github.com/almende/vis/releases

**Comment by Vity01** [comment]
Hmmms, the project was moved and modularized. Now there are several more components like 
https://github.com/visjs/vis-network which has the 5.1.1 version...

**Comment by jamesward** [comment]
Is there a single visjs package based on these?  If not, it might be easier for you to deploy the NPM WebJars: https://www.webjars.org

**Comment by Vity01** [comment]
I don't see it. Maybe the correct solution is to create several separate packages. What do you think?

**Comment by jamesward** [comment]
Click the "Add a WebJar" button and see if you can deploy the `vis-network` NPM package.

**Comment by Vity01** [comment]
It's working. Deploying and processing a new version. Thank you for your assistance.
